#
#   Copyright (C) 2000 Free Software Foundation, Inc.
#
#   Author: Nicola Pero <n.pero@mi.flashnet.it>
#
#   This file is part of JIGS, the GNUstep Java Interface.
#
#   This library is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#   
#   You should have received a copy of the GNU General Public
#   License along with this library; see the file COPYING.LIB.
#   If not, write to the Free Software Foundation,
#   59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

include $(GNUSTEP_MAKEFILES)/common.make

DOCUMENT_NAME = Manual

Manual_LATEX_FILES =      \
Manual.tex                \
TitlePage.tex             \
Introduction.tex          \
Overview.tex              \
ProgrammingInJava.tex     \
WrappingObjcLibraries.tex 
#AccessingJavaFromObjc.tex

Manual_DOC_INSTALL_DIR = Developer/JIGS/Manual

include $(GNUSTEP_MAKEFILES)/documentation.make

