#!/bin/sh
# Quick hack to allow people try everything without installing
#
#   Copyright (C) 2000 Free Software Foundation, Inc.
#
#   Author:  Nicola Pero <n.pero@mi.flashnet.it>
#   Date: July 2000, September 2000
#   
#   This file is part of GNUstep.
#   
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#   
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. */

#
# WARNING: If you want to use the debug version, wipe out the not-debug
# version first.  This is peculiar to this little hack.
#

# Load the LD_LIBRARY_PATH for GNUstep stuff
. $GNUSTEP_MAKEFILES/ld_lib_path.sh

# Quick hack at a suffix
suffix=obj/$GNUSTEP_HOST_CPU/$GNUSTEP_HOST_OS/gnu-gnu-gnu/
wrapper_dir=JavaWrapper/

# Path to the wrapping library classes
export CLASSPATH=./:../Library/$wrapper_dir/Java/:$CLASSPATH
# Path to NameTest.A.so, the wrapping library
LD_LIBRARY_PATH=../Library/$wrapper_dir/Objc/$suffix:$LD_LIBRARY_PATH
# Path to NameTest.so, the real library
LD_LIBRARY_PATH=../Library/$suffix:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH

java NameTestApp

