#
#  GNUstep Java Interface Library, makefile for Java classes
#  
#  Copyright (C) 2000 Free Software Foundation, Inc.
#
#  Written by: Nicola Pero <nicola@brainstorm.co.uk>
#
#  This file is part of the GNUstep Java Interface Library.
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Library General Public
#  License as published by the Free Software Foundation; either
#  version 2 of the License, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
#  Library General Public License for more details.
#
#  You should have received a copy of the GNU Library General Public
#  License along with this library; if not, write to the Free
#  Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111 USA
#

include $(GNUSTEP_MAKEFILES)/common.make

JAVA_PACKAGE_NAME = gnu.gnustep.java

gnu.gnustep.java_JAVA_FILES =                 \
   gnu/gnustep/java/GSJNIMethods.java         \
   gnu/gnustep/java/JIGS.java                 \
   gnu/gnustep/base/NSException.java          \
   gnu/gnustep/base/NSObject.java             \
   gnu/gnustep/base/GSInitializationType.java \
   gnu/gnustep/base/NSPoint.java              \
   gnu/gnustep/base/NSRange.java              \
   gnu/gnustep/base/NSRect.java               \
   gnu/gnustep/base/NSSize.java        

gnu.gnustep.java_JAVA_JNI_FILES =       \
   gnu/gnustep/java/JIGS.java           \
   gnu/gnustep/base/NSObject.java

include $(GNUSTEP_MAKEFILES)/java.make
